### PR TITLE
Add UnsafeInheritance wart

### PR DESCRIPTION
**Pull request by tim-zh**
from [#284](https://github.com/wartremover/wartremover/pull/284)

### CODE REVIEW

**Comment by tim-zh** [comment]
depends on #11

**Comment by amanjpro** [comment]
Thank you for the wart. The build is broken if you could fix it. Also, I believe you could disable overriding non final methods. Or you think this can be a separate wart?

**Comment by amanjpro** [comment]
Oh, just saw the dependency comment. Could you debase it with master please?

**Comment by tim-zh** [comment]
@amanjpro Good idea, I'll look into it.

**Comment by tim-zh** [comment]
Unfortunately, 2.10 Symbol API lacks public `isAbstract`.

**Comment by amanjpro** [comment]
True, but still you can check against the flag, there is a handy way to do it `_.hasFlag(ABSTRSCT)`

**Comment by tim-zh** [comment]
As I'm aware, it's a Tree API feature, while I have the following: `(t: DefDef).symbol.allOverriddenSymbols.exists((x: Symbol) => ...)`

**Comment by amanjpro** [comment]
What you could do is whenever you see a `DefDef` see if it has `OVERRIDE` flag, and disable it

**Comment by tim-zh** [comment]
That wouldn't work here:
```
trait T { def f(): Unit }
class C extends T { override def f() = {} }
```

**Comment by tim-zh** [comment]
It reminds me of another idea: make `override` mandatory, even if parent member is abstract. I saw several bugs caused by this.

**Pull request merged**
